import LegalPage from "../components/common/LegalPage";

const CookiePolicy = () => {
 const data = {
  title: "Cookie Policy",
  date: "Oct 18, 2024",
  sections: [
    {
      heading: "1. Introduction",
      paragraphs: [
        `At Saasboost, we use cookies and other tracking technologies to enhance your experience on our Ads manager platform. This Cookie Policy explains how we use cookies, the types of cookies we use, and how you can manage your cookie preferences.`,
      ],
    },
    {
      heading: "2. What are Cookies?",
      paragraphs: [
        `Cookies are small text files that are stored on your device when you visit a website. They help us understand how you interact with our platform, allowing us to improve your experience and provide you with more personalized services.`,
      ],
    },
    {
      heading: "3. How We Use Cookies",
      paragraphs: [`We use cookies for several purposes:`],
      list: [
        <>
          <span className="font-medium">Strictly Necessary Cookies:</span> These cookies are essential for the proper functioning of our platform. They enable you to log in, access secure areas, and use various features of the Service.
        </>,
        <>
          <span className="font-medium">Performance Cookies:</span> These cookies help us understand how users interact with our platform. They provide insights into usage patterns, which we use to improve the performance and user experience of our Service.
        </>,
        <>
          <span className="font-medium">Functional Cookies:</span> These cookies allow us to remember your preferences and settings, such as your login details, to enhance your experience and provide personalized content.
        </>,
        <>
          <span className="font-medium">Marketing Cookies:</span> These cookies help us deliver relevant advertisements and marketing messages. They also allow us to limit the frequency of advertisements you see.
        </>,
      ],
    },
    {
      heading: "4. Types of Cookies",
      list: [
        <>
          <span className="font-medium">Session Cookies:</span> These temporary cookies are deleted when you close your browser. They are used for session management and to understand if a user is a new visitor or a returning visitor.
        </>,
        <>
          <span className="font-medium">Persistent Cookies:</span> These cookies remain on your device for a specified period. They help us understand user behavior over time and provide insights into how users engage with our platform.
        </>,
      ],
    },
    {
      heading: "5. Cookie Management",
      paragraphs: [
        `You have the ability to accept or decline the use of cookies. Most web browsers automatically accept cookies, but you can modify your browser settings to decline all cookies or to notify you each time a cookie is tendered. However, if you decline cookies, you may experience reduced functionality on our Service.`,
      ],
    },
    {
      heading: "6. Third-Party Cookies",
      paragraphs: [
        <>
          We work with third-party vendors, such as{" "}
          <a href="#" className="text-link hover:underline hover:text-link-hover">
            Google Analytics
          </a>{" "}
          , to collect anonymous data about how users interact with our platform. These third-party cookies help us understand user behavior and improve our services.
        </>,
      ],
    },
    {
      heading: "7. Google Analytics",
      paragraphs: [
         <>
          Our platform uses{" "}
          <a href="#" className="text-link hover:underline hover:text-link-hover">
            Google Analytics
          </a>{" "}
          , a web analytics service provided by Google, Inc. Google Analytics uses cookies to help us analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators, and providing other services relating to website activity and internet usage.
        </>,
      ],
    },
    {
      heading: "8. Changes to This Cookie Policy",
      paragraphs: [
        `We reserve the right to modify this Cookie Policy at any time. Changes and clarifications will take effect immediately upon their posting on this page. You are advised to review this Cookie Policy periodically for any changes.`,
      ],
    },
    {
      heading: "9. Contact Us",
      paragraphs: [
        `If you have any questions about this Cookie Policy, please contact us at [Your Contact Information]. We are committed to protecting your privacy and ensuring that you have a positive experience on our platform.`,
      ],
    },
  ],
};


  return <LegalPage {...data} />;
};

export default CookiePolicy;
